# Generated by Django 6.0 on 2026-02-05 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_commande_elementcommande_elementpanier'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementcommande',
            name='prix',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='elementpanier',
            unique_together={('panier', 'produit')},
        ),
    ]
