# Generated by Django 6.0 on 2026-02-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_elementcommande_prix_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('attente', 'En attente de confirmation'), ('confirmee', 'Confirmée par téléphone'), ('livree', 'Livrée au client'), ('annulee', 'Annulée'), ('refusee', 'Refusée à la livraison')], default='attente', max_length=20),
        ),
    ]
