# Generated by Django 6.0 on 2026-02-06 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='note',
            field=models.IntegerField(default=5),
        ),
    ]
