# Generated by Django 6.0 on 2026-02-07 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_commentaire_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='produit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='shop.product'),
            preserve_default=False,
        ),
    ]
