# Generated by Django 6.0 on 2026-02-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_commentaire_produit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confiance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icone', models.CharField(max_length=50)),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
